config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'admin/dashboard#index'

  resources :locations
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many_attached :images

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  scope :published, -> { where(published: true) }


  def publish!
    self.update! published: true
  end

  def unpublish!
    self.update! published: false
  end

  def toggle_publication!
    self.published? ? unpublish! : publish!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocacionesYa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations</h1>

<ul>
  <% @locations.each do |location| %>
    <li>
      <%= link_to(location.name, location_path(location)) %>
    </li>
  <% end %>

</ul>

app/views/locations/show.html.erb
<h1> <%= @location.name %>

<h2> Address </h4>
<%= @location.address %>

<h2> Pictures </h4>
<ul>
  <% @location.images.includes(:blob).each do |image| %>
    <li><%= image_tag image.variant(resize: '1024x768') %></li>
  <% end %>
</ul>